version: '3'
services:

  cutlerweb:
    image: registry.rschneider.hu/admin/cutlergyor:0.0.34
    restart: always
    networks:
      cutler_network:
    ports:
      - "40001:80"
      - "40002:443"
    volumes:
      - cutler_photos:/var/www/html/cutler/frontend/web/uploads/profile
    environment:
      FITNESS_DB_HOST: "$FITNESS_DB_HOST"
      FITNESS_DB_NAME: "$FITNESS_DB_NAME"
      FITNESS_DB_PORT: "$FITNESS_DB_PORT"
      FITNESS_DB_USERNAME: "$FITNESS_DB_USERNAME"
      FITNESS_DB_PASSWORD: "$FITNESS_DB_PASSWORD"
      FITNESS_MAIL_HOST: "$FITNESS_MAIL_HOST"
      FITNESS_MAIL_PORT: "$FITNESS_MAIL_PORT"
      FITNESS_MAIL_USERNAME: "$FITNESS_MAIL_USERNAME"
      FITNESS_MAIL_PASSWORD: "$FITNESS_MAIL_PASSWORD"
      FITNESS_REST_ALLOW_VERIFY_ONLY: "$FITNESS_REST_ALLOW_VERIFY_ONLY"

#  cutlerdb:
#    image: mariadb:10.1
#    networks:
#      cutler_network:
#    volumes:
#      - cutler_mariadb:/var/lib/mysql
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: cutler
#      MYSQL_DATABASE: cutler_prod2
#      MYSQL_USER: cutler_prod
#      MYSQL_PASSWORD: cutler_prod
#
#  cutlermail:
#    image: reachfive/fake-smtp-server
#    networks:
#      cutler_network:

volumes:
  cutler_photos: {}
#  cutler_mariadb: {}

networks:
  cutler_network:

